// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	TUser
	TLevelConfig
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// "gift_bought":[],"collect":[],"map_gift":[],skin":""
type TUser struct {
	Uid          int32  `protobuf:"varint,1,opt,name=uid" json:"uid"`
	Password     string `protobuf:"bytes,2,opt,name=password" json:"password"`
	Machine      string `protobuf:"bytes,3,opt,name=machine" json:"machine"`
	Coin         int32  `protobuf:"varint,4,opt,name=coin" json:"coin"`
	Energy       int32  `protobuf:"varint,5,opt,name=energy" json:"energy"`
	MaxEnergy    int32  `protobuf:"varint,6,opt,name=max_energy,json=maxEnergy" json:"max_energy"`
	LastRecover  int64  `protobuf:"varint,7,opt,name=last_recover,json=lastRecover" json:"last_recover"`
	DayRecover   int32  `protobuf:"varint,8,opt,name=day_recover,json=dayRecover" json:"day_recover"`
	LastStar     int32  `protobuf:"varint,9,opt,name=last_star,json=lastStar" json:"last_star"`
	CostStar     int32  `protobuf:"varint,10,opt,name=cost_star,json=costStar" json:"cost_star"`
	MedalLv      int32  `protobuf:"varint,11,opt,name=medal_lv,json=medalLv" json:"medal_lv"`
	Icon         int32  `protobuf:"varint,12,opt,name=icon" json:"icon"`
	Stars        int32  `protobuf:"varint,13,opt,name=stars" json:"stars"`
	Nick         string `protobuf:"bytes,14,opt,name=nick" json:"nick"`
	Level        int32  `protobuf:"varint,15,opt,name=level" json:"level"`
	Exp          int32  `protobuf:"varint,16,opt,name=exp" json:"exp"`
	ComCardIndex int32  `protobuf:"varint,17,opt,name=comCardIndex" json:"comCardIndex"`
	Bind         int32  `protobuf:"varint,18,opt,name=bind" json:"bind"`
	Exchange     int32  `protobuf:"varint,19,opt,name=exchange" json:"exchange"`
}

func (m *TUser) Reset()                    { *m = TUser{} }
func (m *TUser) String() string            { return proto.CompactTextString(m) }
func (*TUser) ProtoMessage()               {}
func (*TUser) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TUser) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *TUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TUser) GetMachine() string {
	if m != nil {
		return m.Machine
	}
	return ""
}

func (m *TUser) GetCoin() int32 {
	if m != nil {
		return m.Coin
	}
	return 0
}

func (m *TUser) GetEnergy() int32 {
	if m != nil {
		return m.Energy
	}
	return 0
}

func (m *TUser) GetMaxEnergy() int32 {
	if m != nil {
		return m.MaxEnergy
	}
	return 0
}

func (m *TUser) GetLastRecover() int64 {
	if m != nil {
		return m.LastRecover
	}
	return 0
}

func (m *TUser) GetDayRecover() int32 {
	if m != nil {
		return m.DayRecover
	}
	return 0
}

func (m *TUser) GetLastStar() int32 {
	if m != nil {
		return m.LastStar
	}
	return 0
}

func (m *TUser) GetCostStar() int32 {
	if m != nil {
		return m.CostStar
	}
	return 0
}

func (m *TUser) GetMedalLv() int32 {
	if m != nil {
		return m.MedalLv
	}
	return 0
}

func (m *TUser) GetIcon() int32 {
	if m != nil {
		return m.Icon
	}
	return 0
}

func (m *TUser) GetStars() int32 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *TUser) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *TUser) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *TUser) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *TUser) GetComCardIndex() int32 {
	if m != nil {
		return m.ComCardIndex
	}
	return 0
}

func (m *TUser) GetBind() int32 {
	if m != nil {
		return m.Bind
	}
	return 0
}

func (m *TUser) GetExchange() int32 {
	if m != nil {
		return m.Exchange
	}
	return 0
}

type TLevelConfig struct {
	ID      int32  `protobuf:"varint,1,opt,name=ID" json:"ID"`
	Target  int32  `protobuf:"varint,2,opt,name=target" json:"target"`
	Percent int32  `protobuf:"varint,3,opt,name=percent" json:"percent"`
	Award   string `protobuf:"bytes,4,opt,name=award" json:"award"`
	Score   string `protobuf:"bytes,5,opt,name=score" json:"score"`
}

func (m *TLevelConfig) Reset()                    { *m = TLevelConfig{} }
func (m *TLevelConfig) String() string            { return proto.CompactTextString(m) }
func (*TLevelConfig) ProtoMessage()               {}
func (*TLevelConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TLevelConfig) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *TLevelConfig) GetTarget() int32 {
	if m != nil {
		return m.Target
	}
	return 0
}

func (m *TLevelConfig) GetPercent() int32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *TLevelConfig) GetAward() string {
	if m != nil {
		return m.Award
	}
	return ""
}

func (m *TLevelConfig) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func init() {
	proto.RegisterType((*TUser)(nil), "protos.TUser")
	proto.RegisterType((*TLevelConfig)(nil), "protos.TLevelConfig")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x95, 0xa4, 0x4e, 0xe2, 0x49, 0x28, 0x65, 0x41, 0x68, 0x00, 0x21, 0x42, 0x4e, 0x39,
	0x71, 0xe1, 0x11, 0x5a, 0x0e, 0x91, 0x7a, 0x5a, 0xca, 0x39, 0xda, 0xee, 0x0e, 0xa9, 0x85, 0xbd,
	0x6b, 0xed, 0xba, 0xa9, 0x23, 0xf1, 0xca, 0xbc, 0x03, 0x9a, 0x59, 0xbb, 0x52, 0x4f, 0x9e, 0xff,
	0xff, 0x46, 0x63, 0xcf, 0xfc, 0x06, 0x78, 0x4c, 0x14, 0xbf, 0xb5, 0x31, 0x74, 0x41, 0xcd, 0xe5,
	0x91, 0xb6, 0xff, 0x66, 0x50, 0xdc, 0xfd, 0x4a, 0x14, 0xd5, 0x15, 0xcc, 0x1e, 0x2b, 0x87, 0x93,
	0xcd, 0x64, 0x57, 0x68, 0x2e, 0xd5, 0x47, 0x58, 0xb6, 0x26, 0xa5, 0xa7, 0x10, 0x1d, 0x4e, 0x37,
	0x93, 0x5d, 0xa9, 0x9f, 0xb5, 0x42, 0x58, 0x34, 0xc6, 0x3e, 0x54, 0x9e, 0x70, 0x26, 0x68, 0x94,
	0x4a, 0xc1, 0x85, 0x0d, 0x95, 0xc7, 0x0b, 0x19, 0x24, 0xb5, 0x7a, 0x0f, 0x73, 0xf2, 0x14, 0x8f,
	0x67, 0x2c, 0xc4, 0x1d, 0x94, 0xfa, 0x0c, 0xd0, 0x98, 0xfe, 0x30, 0xb0, 0xb9, 0xb0, 0xb2, 0x31,
	0xfd, 0x8f, 0x8c, 0xbf, 0xc2, 0xba, 0x36, 0xa9, 0x3b, 0x44, 0xb2, 0xe1, 0x44, 0x11, 0x17, 0x9b,
	0xc9, 0x6e, 0xa6, 0x57, 0xec, 0xe9, 0x6c, 0xa9, 0x2f, 0xb0, 0x72, 0xe6, 0xfc, 0xdc, 0xb1, 0x94,
	0x11, 0xe0, 0xcc, 0x79, 0x6c, 0xf8, 0x04, 0xa5, 0xcc, 0x48, 0x9d, 0x89, 0x58, 0x0a, 0x5e, 0xb2,
	0xf1, 0xb3, 0x33, 0x02, 0x6d, 0x18, 0x21, 0x64, 0xc8, 0x86, 0xc0, 0x0f, 0xb0, 0x6c, 0xc8, 0x99,
	0xfa, 0x50, 0x9f, 0x70, 0x25, 0x6c, 0x21, 0xfa, 0xf6, 0xc4, 0x3b, 0x56, 0x36, 0x78, 0x5c, 0xe7,
	0x1d, 0xb9, 0x56, 0xef, 0xa0, 0xe0, 0x31, 0x09, 0x5f, 0x89, 0x99, 0x05, 0x77, 0xfa, 0xca, 0xfe,
	0xc1, 0x4b, 0x39, 0x92, 0xd4, 0xdc, 0x59, 0xd3, 0x89, 0x6a, 0x7c, 0x9d, 0x3b, 0x45, 0xf0, 0xfd,
	0xa9, 0x6f, 0xf1, 0x2a, 0xdf, 0x9f, 0xfa, 0x56, 0x6d, 0x61, 0x6d, 0x43, 0x73, 0x6d, 0xa2, 0xdb,
	0x7b, 0x47, 0x3d, 0xbe, 0x11, 0xf4, 0xc2, 0xe3, 0xf9, 0xf7, 0x95, 0x77, 0xa8, 0xf2, 0x97, 0x70,
	0xcd, 0xb9, 0x51, 0x6f, 0x1f, 0x8c, 0x3f, 0x12, 0xbe, 0xcd, 0x4b, 0x8d, 0x7a, 0xfb, 0x17, 0xd6,
	0x77, 0xb7, 0xfc, 0xbe, 0xeb, 0xe0, 0x7f, 0x57, 0x47, 0x75, 0x09, 0xd3, 0xfd, 0xcd, 0x10, 0xfa,
	0x74, 0x7f, 0xc3, 0x49, 0x75, 0x26, 0x1e, 0xa9, 0x93, 0xc4, 0x0b, 0x3d, 0x28, 0xce, 0xbb, 0xa5,
	0x68, 0xc9, 0x77, 0x92, 0x77, 0xa1, 0x47, 0xc9, 0xdb, 0x98, 0x27, 0x13, 0x9d, 0x04, 0x5e, 0xea,
	0x2c, 0xe4, 0x1a, 0x36, 0x44, 0x92, 0xc0, 0x4b, 0x9d, 0xc5, 0x7d, 0xfe, 0xeb, 0xbe, 0xff, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0x94, 0x8f, 0x60, 0x48, 0x8a, 0x02, 0x00, 0x00,
}
